USE schedule;

CREATE TABLE Schedules
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 id',
    name VARCHAR(50) NOT NULL COMMENT '작성자 이름',
    title VARCHAR(50) NOT NULL COMMENT '일정 제목',
    contents VARCHAR(100) NOT NULL COMMENT '일정 내용',
    password VARCHAR(50) NOT NULL COMMENT '일정 비밀번호',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '일정 작성일',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '일정 수정일'
);